"""Exploratory evaluation of the TZ phonetic generator.

1. Audit: rule engine vs every observed TZ mapping entry.
2. Corpus run: all Hayagriva passages from the generated Publication Read Model.
3. Gap list: syllable types without confirming TZ evidence, by frequency.
4. Comparison with the six unreviewed Reader pronunciation examples.

Outputs go to data/derived/phonetics-research/.
"""

from __future__ import annotations

import csv
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import tz_phonetics as tz  # noqa: E402

OUT = tz.REPOSITORY / "data/derived/phonetics-research"
PUBLICATION = tz.REPOSITORY / "web/hayagriva-reader/src/generated/publication.json"


def audit(gen: tz.Generator) -> list[dict]:
    rows = []
    for syl, entry in gen.mapping.items():
        if entry["resolution_origin"] != "observed_TZ":
            continue
        rule_value, rule_origin, rule_note = gen.rule(syl, "x")
        value, origin, note = (None, "skipped_sanskrit", "") if rule_origin == "rule_sanskrit" else \
            tz.evidence_decision(entry, rule_value)
        rows.append({
            "tibetan": syl, "variants": entry["variants"], "mapping_resolved": entry["resolved_tz_phonetic"],
            "hayagriva_mode": entry["hayagriva_mode"], "rule": rule_value or "", "rule_origin": rule_origin,
            "decision": value or "", "decision_origin": origin, "note": note or rule_note,
            "mapping_changed": (value or "") != entry["resolved_tz_phonetic"],
            "inventory_total": int(entry["inventory_total"] or 0),
        })
    return rows


ORIGIN_TEXT = {
    "observed_TZ": "TZ evidence overrides the rule (majority of plausible observations)",
    "rule_contested": "rule output kept; the only TZ observations disagree (mostly OCR/alignment errors)",
    "rule_tibetan": "no TZ evidence; proposed by the Tibetan orthography rules",
    "rule_sanskrit": "no TZ evidence; Sanskrit/mantra transliteration rules",
    "unresolved": "no proposal",
}


def write_gap_review(gaps) -> None:
    lines = ["# Phonetics gap review (generated)", "",
             "Generated by `scripts/phonetics_research/evaluate.py`. Every syllable type in the Hayagriva",
             "corpus that is *not* confirmed by TZ evidence or a mantra exception. `proposal` is the",
             "generator output. Reviewers: correct a value by adding it to",
             "`scripts/phonetics_research/overrides.json` (`{\"<tibetan>\": {\"phonetic\": ..., \"reason\": ...}}`).",
             ""]
    by_origin = defaultdict(list)
    for syl, info in gaps:
        by_origin[info["origin"]].append((syl, info))
    for origin in ("observed_TZ", "rule_contested", "rule_tibetan", "rule_sanskrit", "unresolved"):
        items = by_origin.get(origin, [])
        tokens = sum(i["count"] for _, i in items)
        lines += [f"## {origin} — {len(items)} types / {tokens} tokens", "", ORIGIN_TEXT[origin], "",
                  "| tibetan | proposal | count | first passage | note |", "|---|---|---:|---|---|"]
        for syl, info in items:
            note = info["note"].replace("|", "/")
            lines.append(f"| {syl} | {info['phonetic']} | {info['count']} | {info['passages'][0]} | {note} |")
        lines.append("")
    (OUT / "gap-review.md").write_text("\n".join(lines), encoding="utf-8")


def passages():
    publication = json.loads(PUBLICATION.read_text(encoding="utf-8"))
    for section in publication["sections"]:
        for passage in section["passages"]:
            text = "\n".join(b["text"] for b in passage["source"]["blocks"])
            yield passage["id"], text, passage.get("pronunciation")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    gen = tz.Generator()

    # 1. audit ------------------------------------------------------------
    rows = audit(gen)
    with (OUT / "mapping-audit.csv").open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(sorted(rows, key=lambda r: (r["decision_origin"], -r["inventory_total"])))
    audit_counts = Counter(r["decision_origin"] for r in rows)
    changed = sum(r["mapping_changed"] for r in rows)

    # 2. corpus -----------------------------------------------------------
    token_origin = Counter()
    type_info: dict[str, dict] = {}
    rendered = []
    for pid, text, _ in passages():
        phrases = gen.text(text)
        rendered.append({"passage": pid, "tibetan": text, "phonetic": tz.render(phrases),
                         "syllables": [[r.tibetan, r.phonetic, r.origin] for p in phrases for r in p]})
        for phrase in phrases:
            for r in phrase:
                token_origin[r.origin] += 1
                info = type_info.setdefault(r.tibetan, {"phonetic": r.phonetic, "origin": r.origin,
                                                        "note": r.note, "count": 0, "passages": []})
                info["count"] += 1
                if pid not in info["passages"]:
                    info["passages"].append(pid)
    (OUT / "hayagriva-generated.json").write_text(json.dumps(rendered, ensure_ascii=False, indent=1),
                                                  encoding="utf-8")
    with (OUT / "hayagriva-generated.txt").open("w", encoding="utf-8") as fh:
        for item in rendered:
            fh.write(f"## {item['passage']}\n{item['tibetan']}\n→ {item['phonetic']}\n\n")
    type_origin = Counter(i["origin"] for i in type_info.values())

    # 3. gaps -------------------------------------------------------------
    gap_origins = {"rule_tibetan", "rule_contested", "rule_sanskrit", "unresolved", "observed_TZ"}
    gaps = sorted(((s, i) for s, i in type_info.items() if i["origin"] in gap_origins),
                  key=lambda si: (si[1]["origin"], -si[1]["count"], si[0]))
    with (OUT / "gap-syllables.csv").open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["tibetan", "phonetic", "origin", "count", "first_passages", "note"])
        for syl, info in gaps:
            writer.writerow([syl, info["phonetic"], info["origin"], info["count"],
                             " ".join(info["passages"][:4]), info["note"]])

    write_gap_review(gaps)

    # 4. examples ---------------------------------------------------------
    examples = []
    for pid, text, pron in passages():
        if not pron:
            continue
        for line in pron["lines"]:
            ours = tz.render(gen.text(line["tibetan"])).replace(" / ", " ")
            examples.append({"passage": pid, "tibetan": line["tibetan"].strip(),
                             "reader_example": line["pronunciation"], "generator": ours})
    (OUT / "reader-example-comparison.json").write_text(json.dumps(examples, ensure_ascii=False, indent=1),
                                                        encoding="utf-8")

    summary = {
        "audit_observed_entries": len(rows), "audit_decisions": dict(audit_counts),
        "audit_changed_vs_mapping_resolved": changed,
        "corpus_passages": len(rendered), "corpus_tokens": sum(token_origin.values()),
        "corpus_types": len(type_info), "token_origin": dict(token_origin), "type_origin": dict(type_origin),
        "types_in_mapping": sum(1 for s in type_info if s in gen.mapping),
    }
    (OUT / "summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=1), encoding="utf-8")
    print(json.dumps(summary, ensure_ascii=False, indent=1))


if __name__ == "__main__":
    main()
